FROM cassandra:$CASSADNRA_VERSION

# Install cUrl
RUN apt-get update && apt-get install --yes curl

# Add cassandra-lucene-index jar from maven
RUN cd /usr/share/cassandra/lib && \
  curl -LO https://repo1.maven.org/maven2/com/stratio/cassandra/cassandra-lucene-index-plugin/$STRATIO_PLUGIN_VERSION/cassandra-lucene-index-plugin-$STRATIO_PLUGIN_VERSION.jar
